set nocompatible              " Disable Vi compatibility
filetype off                  " required


" ============= Vundle ============="

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'
Plugin 'fatih/vim-go'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" ============= Vundle ============="


syntax enable

set number "activate line number



"---------------Visual----------------"
colorscheme onedark
set backspace=indent,eol,start "Make backspace behave like every other editor
set t_CO=256 "Use 256 colors

"---------------Search----------------"
set hlsearch "highlight search result
set incsearch 



"---------------Mappings----------------"
map <Enter> o<ESC>






"---------------Auto-Commands-----------"

"Automatically source the Vimrc file on save."
autocmd BufWritePost .vimrc source %
